# ###################
# Intro message
print('*'*51)
print('*'*51)
print('*'*5, ' '*39, '*'*5)
print('*'*5, ' '*8, '~ MADLIBS™ CLI GAME ~', ' '*8, '*'*5)
print('*'*5, ' '*39, '*'*5)
print('*'*5, ' '*39, '*'*5)
print('*'*5, ' '*4, 'Respond to the prompts below!', ' '*4, '*'*5)
print('*'*5, ' '*3, 'Prompts may ask you for a noun,', ' '*3, '*'*5)
print('*'*5, ' '*3, 'verb, pronoun, first name, etc.', ' '*3, '*'*5)
print('*'*5, ' '*39, '*'*5)
print('*'*5, ' '*2, 'MadLibs™ will use your responses,', ' '*2, '*'*5)
print('*'*5, ' '*4, 'to create a wacky cool story!', ' '*4, '*'*5)
print('*'*5, ' '*9, "Type 'quit' to exit.", ' '*8, '*'*5)
print('*'*5, ' '*39, '*'*5)
print('*'*51)
print('*'*51)

file = open("example.txt")
print(file.read().find("{Adjective}", 30))
